inherit: [fiasco]

depends:
    - tools:
          target-toolchain: host-compat-toolchain
      depends:
          - libs::ncurses-dev

buildSetup: |
    # Calls the fiasco savedefconfig target
    #
    # Especially in the sandbox this can be tricky. Provide some convenience method.
    fiascoSavedefconfig()
    {
        makeParallel \
            HOSTCC="gcc" \
            savedefconfig
    }

    # Calls the fiasco menuconfig target
    #
    # Especially in the sandbox this can be tricky. Provide some convenience method.
    fiascoMenuconfig()
    {
        NCDEP=${BOB_DEP_PATHS[libs::ncurses-dev]}/usr
        makeParallel \
            HOSTCC="gcc" \
            HOSTCFLAGS="-I${NCDEP}/include -DCURSES_LOC=\"<ncurses.h>\" -DLOCALE $(pkg-config --cflags ncurses)" \
            HOSTLDLIBS="-L${NCDEP}/lib $(pkg-config --libs ncurses)" \
            menuconfig
        #  Always save a defconfig
        fiascoSavedefconfig
    }
